services:

    photopea:
        image: shtse8/photopea:1.0
        container_name: photopea
        ports:
            - '8887:8887'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Madrid
        restart: unless-stopped

        